version: "3.9"
services:

  postgres:
    image: postgres:11.5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
#  web:
#    build:
#      context: .
#      args:
#        environment: development
#      dockerfile: Dockerfile
#    volumes:
#      - .:/app
#    env_file:
#      - .env
#    ports:
#      - "3000:3000"
#    environment:
#      RAILS_ENV: development
#      DATABASE_HOST: postgres
#      DATABASE_NAME: apostas_development
#      DATABASE_USER: apostas
#      DATABASE_PASSWORD: password
#    depends_on:
#      - postgres
#    links:
#      - postgres

volumes:
  db_data:
