version: "3.9"
services:

  postgres:
    image: postgres:11.5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  task-manager-backend:
    build:
      context: ./task-manager-backend-ruby-on-rails
      target: development
    volumes:
      - ./task-manager-backend-ruby-on-rails:/app
    ports:
      - "3001:3001"
    environment:
      RAILS_ENV: development
      PORT: 3001
      DATABASE_HOST: postgres
      DATABASE_NAME: task_manager_development
      DATABASE_USER: task_manager
      DATABASE_PASSWORD: password
      MAIL_HOST: maildev
      MAIL_PORT: 1025
      RAILS_MASTER_KEY: 40c913eb8b7cf6f436d21289712b73f4
    depends_on:
      - postgres
    links:
      - postgres
  task-manager-frontend:
      build:
        context: ./task-manager-frontend-react
        target: development
      ports:
        - "3000:3000"
      volumes:
        - ./task-manager-frontend-react:/app
        - /app/node_modules
      environment:
        - NODE_ENV=development
        - VITE_API_URL=http://localhost:3001
      depends_on:
        - task-manager-backend

volumes:
  db_data:
